# Generated by Django 5.1.7 on 2025-04-26 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хозяин'),
        ),
        migrations.AddField(
            model_name='dogparent',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed', verbose_name='Порода родителя'),
        ),
        migrations.AddField(
            model_name='dogparent',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog'),
        ),
    ]
