# Generated by Django 5.1.7 on 2025-04-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='sign_of_reviews',
            new_name='sign_of_review',
        ),
    ]
